target: mojito.archs.vqvae.VQVae
params:
  nfeats: ${DATASET.NFEATS_MOTION}
  code_num: 1024
  code_dim: 512
  output_emb_width: 512
  down_t: 2
  stride_t: 2
  width: 512
  depth: 3
  dilation_growth_rate: 3
  activation: 'relu'
  use_zipf: True